{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wazuh.fullname" . }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "wazuh.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    {{- with .Values.networkPolicy.additionalIngress }}
    {{- toYaml . | nindent 2 }}
    {{- end }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- with .Values.networkPolicy.additionalEgress }}
    {{- toYaml . | nindent 2 }}
    {{- end }}
{{- end -}}
