{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "wazuh.fullname" . }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.backend }}
    kind: ClusterSecretStore
  target:
    name: {{ include "wazuh.fullname" . }}
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- else if not .Values.existingSecret }}
{{- if .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
{{- end -}}
